// Admin-editable default scheduling rules. Every task `generateTasks()` (see scheduler.ts) can
// produce has a corresponding row here (matched by `key`). "fixed" and "ratio" rows are fully
// data-driven (anchor/offset or deadline-ratio are read straight from the row); "special" rows
// have hardcoded date logic in scheduler.ts (multi-meeting branching, cross-task dependencies,
// the deadline-time-of-day conditional) but still take their category/label/owner/enabled from
// here so an admin can rename, reassign, or turn off any default task without a code change.

export type TaskTemplateAnchor = "start" | "workStart" | "deadline";
export type TaskTemplateKind = "fixed" | "ratio" | "special";

export interface TaskTemplateRow {
  key: string;
  sortIndex: number;
  category: string;
  label: string;
  owner: string;
  enabled: boolean;
  kind: TaskTemplateKind;
  // Anchor is either one of the 3 fixed case dates (anchor) or another template's computed date
  // (anchorTaskKey, takes precedence when set) — lets a "fixed" row admit it's really derived
  // from another task (e.g. 服務建議書用印 follows 服務建議書送印, not 投標截止 directly) so
  // editing the parent's rule correctly cascades instead of both being independently pinned to
  // the same case date. See scheduler.ts's resolveFixedDate.
  anchor?: TaskTemplateAnchor;
  anchorTaskKey?: string | null;
  offsetDays?: number;
  ratioPct?: number;
  snap?: boolean;
  milestone?: string | null;
  note?: string;
}

const CAT = {
  A: "會議安排",
  B: "公司內部流程",
  C: "服務建議書製作",
  D: "投標文件蒐集、確認",
  E: "評選作業",
  F: "其他事項",
};

export const DEFAULT_TASK_TEMPLATES: TaskTemplateRow[] = [
  // A. 會議安排
  {
    key: "meeting_recurring",
    sortIndex: 0,
    category: CAT.A,
    label: "例行會議＃",
    owner: "",
    enabled: true,
    kind: "special",
    note: "招標公告後第3天起，每週一次固定星期，到投標截止前7天為止；數量依區間自動產生。",
  },
  {
    key: "kickoff",
    sortIndex: 1,
    category: CAT.A,
    label: "統包啟動會議",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: -7,
  },
  {
    key: "wu",
    sortIndex: 2,
    category: CAT.A,
    label: "吳董設計會議",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 14,
    milestone: "wu",
  },
  {
    key: "prebid",
    sortIndex: 3,
    category: CAT.A,
    label: "標前會",
    owner: "",
    enabled: true,
    kind: "special",
    milestone: "prebid",
    note: "不論契約金額，預設僅安排一場，且須排在投標截止前7天以上（並在吳董設計會議之後至少間隔5天）。",
  },
  {
    key: "notarize",
    sortIndex: 4,
    category: CAT.A,
    label: "實績公證＋統包廠商JV公證合作同意書",
    owner: "",
    enabled: true,
    kind: "special",
    milestone: "notarize",
    note: "投標截止前4天，且需在工程事業簽呈之後。",
  },

  // B. 公司內部流程
  {
    key: "prebid_agreement",
    sortIndex: 5,
    category: CAT.B,
    label: "標前協議書／共同投標協議書確定",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: -7,
  },
  {
    key: "maintenance_application",
    sortIndex: 6,
    category: CAT.B,
    label: "營繕工程備標申請",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 3,
  },
  {
    key: "review_form_contract",
    sortIndex: 7,
    category: CAT.B,
    label: "會辦流程單（契約、投標須知）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 3,
  },
  {
    key: "review_form_prebid",
    sortIndex: 8,
    category: CAT.B,
    label: "會辦流程單（備標團隊標前協議書，不含金額，領標後2~3週）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 18,
  },
  {
    key: "eng_signoff",
    sortIndex: 9,
    category: CAT.B,
    label: "工程事業簽呈（標前協議書含費用、共同投標協議書含費用，標前會前完成）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "prebid",
    offsetDays: -1,
    milestone: "eng_signoff",
  },

  // C. 服務建議書製作
  {
    key: "master",
    sortIndex: 10,
    category: CAT.C,
    label: "服務建議書母片／分工表提供",
    owner: "",
    enabled: true,
    kind: "special",
    note: "招標公告後7~10天內，通常在例行會議#1之後。",
  },
  {
    key: "draft",
    sortIndex: 11,
    category: CAT.C,
    label: "服務建議書初稿繳交",
    owner: "",
    enabled: true,
    kind: "special",
    note: "「母片日+11天」後最近一次例行會議的前一天。",
  },
  {
    key: "proof1",
    sortIndex: 12,
    category: CAT.C,
    label: "服務建議書校正＃1（例行會議彙整）",
    owner: "",
    enabled: true,
    kind: "special",
    note: "同上那次例行會議當天。",
  },
  {
    key: "proof2",
    sortIndex: 13,
    category: CAT.C,
    label: "服務建議書校正＃2",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "print",
    offsetDays: -2,
    milestone: "final_proof",
  },
  {
    key: "print",
    sortIndex: 14,
    category: CAT.C,
    label: "服務建議書送印",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: -2,
    milestone: "print",
  },
  {
    key: "stamp",
    sortIndex: 15,
    category: CAT.C,
    label: "服務建議書用印（含封標）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "print",
    offsetDays: -1,
  },

  // D. 投標文件蒐集、確認
  {
    key: "collect",
    sortIndex: 16,
    category: CAT.D,
    label: "招標公告",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 0,
    snap: false,
    milestone: "collect",
    note: "人為去填寫或是系統判斷招標文件。",
  },
  {
    key: "estimate_start",
    sortIndex: 17,
    category: CAT.D,
    label: "估算作業開始",
    owner: "估算部",
    enabled: true,
    kind: "special",
    note: "建築師提交平立面／剖面／門窗表／外觀材質後一天開始作業。",
  },
  {
    key: "estimate_end",
    sortIndex: 18,
    category: CAT.D,
    label: "完成估算（需於標前會前1週完成）",
    owner: "估算部",
    enabled: true,
    kind: "special",
    note: "估算作業開始後14天。",
  },
  {
    key: "architect_deliver",
    sortIndex: 19,
    category: CAT.D,
    label: "建築師提供平立面／剖面／門窗表／外觀材質",
    owner: "建築師",
    enabled: true,
    kind: "special",
    note: "估算開始日前1天，例行會議＃2會議後1~2天。",
  },
  {
    key: "cost_final",
    sortIndex: 20,
    category: CAT.D,
    label: "投標成本定稿",
    owner: "",
    enabled: true,
    kind: "special",
    note: "第一場標前會前3天。",
  },
  {
    key: "cost_approval",
    sortIndex: 21,
    category: CAT.D,
    label: "內部成本簽核",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "print",
    offsetDays: -1,
  },
  {
    key: "internal_decision",
    sortIndex: 22,
    category: CAT.D,
    label: "內部核決",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "print",
    offsetDays: -1,
  },
  {
    key: "consultant_confirm",
    sortIndex: 23,
    category: CAT.D,
    label: "確認設計顧問委託及顧問團隊（領標後一週內）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "workStart",
    offsetDays: 7,
  },
  {
    key: "qualification_docs",
    sortIndex: 24,
    category: CAT.D,
    label: "投標資格文件彙整（投標截止前一週）",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: -7,
  },
  {
    key: "bid_bond_apply",
    sortIndex: 25,
    category: CAT.D,
    label: "押標金申請",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "start",
    offsetDays: 2,
  },
  {
    key: "bid_bond_obtain",
    sortIndex: 26,
    category: CAT.D,
    label: "取得押標金",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchorTaskKey: "print",
    offsetDays: -1,
  },
  {
    key: "submit_action",
    sortIndex: 27,
    category: CAT.D,
    label: "送件投標",
    owner: "",
    enabled: true,
    kind: "special",
    milestone: "submit_action",
    note: "投標截止前1天；若投標截止是上午（10:00前）則提前一天送件，若投標截止是下午（如17:00）則與投標截止同一天送件。",
  },
  {
    key: "deadline",
    sortIndex: 28,
    category: CAT.D,
    label: "投標截止",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 0,
    snap: false,
    milestone: "deadline",
  },

  // E. 評選作業
  {
    key: "eval_presentation_day",
    sortIndex: 29,
    category: CAT.E,
    label: "施工評選簡報日",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 14,
  },
  {
    key: "final_vendor",
    sortIndex: 30,
    category: CAT.E,
    label: "決選廠商",
    owner: "業主",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 15,
  },
  {
    key: "eval_draft",
    sortIndex: 31,
    category: CAT.E,
    label: "施工評選簡報初稿",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 5,
  },
  {
    key: "eval_final",
    sortIndex: 32,
    category: CAT.E,
    label: "施工評選簡報定稿",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 3,
  },
  {
    key: "eval_rehearsal",
    sortIndex: 33,
    category: CAT.E,
    label: "簡報模擬",
    owner: "",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 2,
  },

  // F. 其他事項
  {
    key: "rfi",
    sortIndex: 34,
    category: CAT.F,
    label: "提出釋疑",
    owner: "備標團隊",
    enabled: true,
    kind: "special",
    note: "投標截止前工期25%（工期以扣除例假日與國定假日的工作天計算），遇假日自動提前至最近工作日。",
  },
  {
    key: "bid_opening",
    sortIndex: 35,
    category: CAT.F,
    label: "開標作業（業主流程）",
    owner: "業主",
    enabled: true,
    kind: "fixed",
    anchor: "deadline",
    offsetDays: 0,
  },
  {
    key: "design_plan_85",
    sortIndex: 36,
    category: CAT.F,
    label: "初步設計規劃",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 85,
  },
  {
    key: "design_v2_60",
    sortIndex: 37,
    category: CAT.F,
    label: "設計圖說V2",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 60,
  },
  {
    key: "design_final_40",
    sortIndex: 38,
    category: CAT.F,
    label: "投標前設計圖說定稿",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 40,
  },
  {
    key: "material_selection_32",
    sortIndex: 39,
    category: CAT.F,
    label: "建材設備選用表",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 32,
  },
  {
    key: "model_100_30",
    sortIndex: 40,
    category: CAT.F,
    label: "建築模型1/100",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 30,
  },
  {
    key: "schedule_final_25",
    sortIndex: 41,
    category: CAT.F,
    label: "工程進度／工序定稿",
    owner: "",
    enabled: true,
    kind: "ratio",
    ratioPct: 25,
  },
];

export function mergeTemplates(overrides: TaskTemplateRow[] | undefined | null): TaskTemplateRow[] {
  if (!overrides || overrides.length === 0) return DEFAULT_TASK_TEMPLATES;
  const byKey = new Map(overrides.map((t) => [t.key, t]));
  const merged = DEFAULT_TASK_TEMPLATES.map((def) => {
    const o = byKey.get(def.key);
    return o ? { ...def, ...o } : def;
  });
  const extra = overrides.filter((t) => !DEFAULT_TASK_TEMPLATES.some((d) => d.key === t.key));
  return [...merged, ...extra].sort((a, b) => a.sortIndex - b.sortIndex);
}
